Updated Docs + Error Handling Page
radon-project/docs pull request #4
Opened 2024-05-31 19:37 UTC by Vardan2009

2024-05-31 19:58 UTC, Almas-Ali commented
Can you please resolve those conflicts?

2024-05-31 20:22 UTC, Almas-Ali commented
Please check in the `radon-project:master` `docs/exceptions.md` and combine this with your `docs/error-handling.md`.

2024-06-01 19:20 UTC, Vardan2009 commented
I think "Error Handling" is a better title for the page

2024-06-01 19:29 UTC, Almas-Ali requested changes

2024-06-01 19:29 UTC, Almas-Ali commented on docs/exceptions.md
> +risky_operation(0)
Please test your code before putting on public docs.

Also follow K&R formatting for writing code in docs.

2024-06-01 20:19 UTC, Almas-Ali approved these changes

2024-06-01 20:20 UTC, merged